### ISSUE TITLE
Error in clean installation 

### ISSUE THREAD

**Issue by raydan** [digitalfruit/limejs#151]
just doing a new installation
error: pathspec 'd823edb' did not match any file(s) known to git.
Failed to clone Closure Library via Git. Discontinuing.

then i try compile helloworld
```
closure\closure\goog\base.js:236: ERROR - illegal i
nitialization of @define variable goog.DISALLOW_TEST_ONLY_CODE
goog.define('goog.DISALLOW_TEST_ONLY_CODE', COMPILED && !goog.DEBUG);
```
after download latest compiler, compile success

compile with -a option, so many schedulemanager.js warning
and i got
"Uncaught SyntaxError: Unexpected token void"
in chrome
point at ..\..\lime\src\director.js:346
```
bin/lime.py build helloworld -o helloworld/compiled/hw_adv.js -m -a
```

**Comment by tonistiigi** [comment]
Should be fixed now. Thanks for reporting. Remove closure directory and run `init` again.
